name: late_provider_issue
description: A Solution for Late init provider issue of Riverpod Providers, the providers which are intially provided with throw UnimplementedError() throws the exception even when overriden before being utilized.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.0.2
  riverpod_annotation: ^1.0.4
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  riverpod_generator: ^1.0.4

flutter:
  uses-material-design: true
